import 'package:untitled1/Utils/dart_classes/zodiac_classes.dart';

List<OfflineZodiacData> allSigns = [
  Aries(
      name: "Aries",
      dateInterval: "21Mar-19Apr",
      logoPicture: 'assets/sign_logos/aries.png',
      index: 0,
      ascendant: 'Pisces',
      element: 'Fire',
      moonSign: 'Scorpio',
      sunSign: 'Aries',
      assetPicture: 'assets/sign_logos/a-aries.png'),
  Taurus(
      name: "Taurus",
      dateInterval: "20Apr-20May",
      logoPicture: 'assets/sign_logos/taurus.png',
      index: 1,
      ascendant: 'Aries',
      element: 'Earth',
      moonSign: 'Taurus',
      sunSign: 'Taurus',
      assetPicture: 'assets/sign_logos/a-taurus.png'),
  Gemini(
      name: "Gemini",
      dateInterval: "21May-20Jun",
      logoPicture: 'assets/sign_logos/gemini.png',
      index: 2,
      ascendant: 'Taurus',
      element: 'Air',
      moonSign: 'Leo',
      sunSign: 'Gemini',
      assetPicture: 'assets/sign_logos/a-gemini.png'),
  Cancer(
      name: "Cancer",
      dateInterval: "21Jun-22Jul",
      logoPicture: 'assets/sign_logos/cancer.png',
      index: 3,
      ascendant: 'Gemini',
      element: 'Water',
      moonSign: 'Virgo',
      sunSign: 'Cancer',
      assetPicture: 'assets/sign_logos/a-cancer.png'),
  Leo(
      name: "Leo",
      dateInterval: "23Jul-22Aug",
      logoPicture: 'assets/sign_logos/leo.png',
      index: 4,
      ascendant: 'Cancer',
      element: 'Fire',
      moonSign: 'Libra',
      sunSign: 'Leo',
      assetPicture: 'assets/sign_logos/a-leo.png'),
  Virgo(
      name: "Virgo",
      dateInterval: "23Aug-22Sep",
      logoPicture: 'assets/sign_logos/virgo.png',
      index: 5,
      ascendant: 'Leo',
      element: 'Earth',
      moonSign: 'Scorpio',
      sunSign: 'Virgo',
      assetPicture: 'assets/sign_logos/a-virgo.png'),
  Libra(
      name: "Libra",
      dateInterval: "23Sep-22Oct",
      logoPicture: 'assets/sign_logos/libra.png',
      index: 6,
      ascendant: 'Virgo',
      element: 'Air',
      moonSign: 'Sagittarius',
      sunSign: 'Libra',
      assetPicture: 'assets/sign_logos/a-libra.png'),
  Scorpio(
      name: "Scorpio",
      dateInterval: "23Oct-21Nov",
      logoPicture: 'assets/sign_logos/scorpio.png',
      index: 7,
      ascendant: 'Libra',
      element: 'Water',
      moonSign: 'Capricorn',
      sunSign: 'Scorpio',
      assetPicture: 'assets/sign_logos/a-scorpio.png'),
  Sagittarius(
      name: "Sagittarius",
      dateInterval: "22Nov-21Dec",
      logoPicture: 'assets/sign_logos/sagittarius.png',
      index: 8,
      ascendant: 'Scorpio',
      element: 'Fire',
      moonSign: 'Aquarius',
      sunSign: 'Sagittarius',
      assetPicture: 'assets/sign_logos/a-sagittarius.png'),
  Capricorn(
      name: "Capricorn",
      dateInterval: "22Dec-19Jan",
      logoPicture: 'assets/sign_logos/capricorn.png',
      index: 9,
      ascendant: 'Sagittarius',
      element: 'Earth',
      moonSign: 'Pisces',
      sunSign: 'Capricorn',
      assetPicture: 'assets/sign_logos/a-capricorn.png'),
  Aquarius(
      name: "Aquarius",
      dateInterval: "20Jan-18Feb",
      logoPicture: 'assets/sign_logos/aquarius.png',
      index: 10,
      ascendant: 'Capricorn',
      element: 'Air',
      moonSign: 'Aries',
      sunSign: 'Aquarius',
      assetPicture: 'assets/sign_logos/a-aquarius.png'),
  Pisces(
      name: "Pisces",
      dateInterval: "19Feb-20Mar",
      logoPicture: 'assets/sign_logos/pisces.png',
      index: 11,
      ascendant: 'Aquarius',
      element: 'Water',
      moonSign: 'Taurus',
      sunSign: 'Pisces',
      assetPicture: 'assets/sign_logos/a-pisces.png')
];
